/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCobrancasIdRouteImport } from './routes/_authenticated/cobrancas.$id'
import { Route as AuthenticatedContasIndexRouteImport } from './routes/_authenticated/contas.index'
import { Route as AuthenticatedContasIdRouteImport } from './routes/_authenticated/contas.$id'
import { Route as ApiPublicPicpayWebhookRouteImport } from './routes/api/public/picpay-webhook'
import { Route as ApiPublicReconcileChargesRouteImport } from './routes/api/public/reconcile-charges'
import { Route as ApiV1ChargesRouteImport } from './routes/api/v1/charges'
import { Route as ApiV1ChargesIdRouteImport } from './routes/api/v1/charges/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCobrancasIdRoute =
  AuthenticatedCobrancasIdRouteImport.update({
    id: '/cobrancas/$id',
    path: '/cobrancas/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasIndexRoute =
  AuthenticatedContasIndexRouteImport.update({
    id: '/contas/',
    path: '/contas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasIdRoute = AuthenticatedContasIdRouteImport.update({
  id: '/contas/$id',
  path: '/contas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPicpayWebhookRoute = ApiPublicPicpayWebhookRouteImport.update({
  id: '/api/public/picpay-webhook',
  path: '/api/public/picpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReconcileChargesRoute =
  ApiPublicReconcileChargesRouteImport.update({
    id: '/api/public/reconcile-charges',
    path: '/api/public/reconcile-charges',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ChargesRoute = ApiV1ChargesRouteImport.update({
  id: '/api/v1/charges',
  path: '/api/v1/charges',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChargesIdRoute = ApiV1ChargesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1ChargesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cobrancas/$id': typeof AuthenticatedCobrancasIdRoute
  '/contas/$id': typeof AuthenticatedContasIdRoute
  '/api/public/picpay-webhook': typeof ApiPublicPicpayWebhookRoute
  '/api/public/reconcile-charges': typeof ApiPublicReconcileChargesRoute
  '/api/v1/charges': typeof ApiV1ChargesRouteWithChildren
  '/contas/': typeof AuthenticatedContasIndexRoute
  '/api/v1/charges/$id': typeof ApiV1ChargesIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/': typeof AuthenticatedIndexRoute
  '/cobrancas/$id': typeof AuthenticatedCobrancasIdRoute
  '/contas/$id': typeof AuthenticatedContasIdRoute
  '/api/public/picpay-webhook': typeof ApiPublicPicpayWebhookRoute
  '/api/public/reconcile-charges': typeof ApiPublicReconcileChargesRoute
  '/api/v1/charges': typeof ApiV1ChargesRouteWithChildren
  '/contas': typeof AuthenticatedContasIndexRoute
  '/api/v1/charges/$id': typeof ApiV1ChargesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cobrancas/$id': typeof AuthenticatedCobrancasIdRoute
  '/_authenticated/contas/$id': typeof AuthenticatedContasIdRoute
  '/api/public/picpay-webhook': typeof ApiPublicPicpayWebhookRoute
  '/api/public/reconcile-charges': typeof ApiPublicReconcileChargesRoute
  '/api/v1/charges': typeof ApiV1ChargesRouteWithChildren
  '/_authenticated/contas/': typeof AuthenticatedContasIndexRoute
  '/api/v1/charges/$id': typeof ApiV1ChargesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/cobrancas/$id'
    | '/contas/$id'
    | '/api/public/asaas-webhook'
    | '/api/public/efi-webhook'
    | '/api/public/inter-webhook'
    | '/api/public/picpay-webhook'
    | '/api/public/reconcile-charges'
    | '/api/v1/charges'
    | '/contas/'
    | '/api/v1/charges/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/configuracoes'
    | '/'
    | '/cobrancas/$id'
    | '/contas/$id'
    | '/api/public/asaas-webhook'
    | '/api/public/efi-webhook'
    | '/api/public/inter-webhook'
    | '/api/public/picpay-webhook'
    | '/api/public/reconcile-charges'
    | '/api/v1/charges'
    | '/contas'
    | '/api/v1/charges/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/configuracoes'
    | '/_authenticated/'
    | '/_authenticated/cobrancas/$id'
    | '/_authenticated/contas/$id'
    | '/api/public/asaas-webhook'
    | '/api/public/efi-webhook'
    | '/api/public/inter-webhook'
    | '/api/public/picpay-webhook'
    | '/api/public/reconcile-charges'
    | '/api/v1/charges'
    | '/_authenticated/contas/'
    | '/api/v1/charges/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicPicpayWebhookRoute: typeof ApiPublicPicpayWebhookRoute
  ApiPublicReconcileChargesRoute: typeof ApiPublicReconcileChargesRoute
  ApiV1ChargesRoute: typeof ApiV1ChargesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cobrancas/$id': {
      id: '/_authenticated/cobrancas/$id'
      path: '/cobrancas/$id'
      fullPath: '/cobrancas/$id'
      preLoaderRoute: typeof AuthenticatedCobrancasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas/': {
      id: '/_authenticated/contas/'
      path: '/contas'
      fullPath: '/contas/'
      preLoaderRoute: typeof AuthenticatedContasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas/$id': {
      id: '/_authenticated/contas/$id'
      path: '/contas/$id'
      fullPath: '/contas/$id'
      preLoaderRoute: typeof AuthenticatedContasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/picpay-webhook': {
      id: '/api/public/picpay-webhook'
      path: '/api/public/picpay-webhook'
      fullPath: '/api/public/picpay-webhook'
      preLoaderRoute: typeof ApiPublicPicpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reconcile-charges': {
      id: '/api/public/reconcile-charges'
      path: '/api/public/reconcile-charges'
      fullPath: '/api/public/reconcile-charges'
      preLoaderRoute: typeof ApiPublicReconcileChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/charges': {
      id: '/api/v1/charges'
      path: '/api/v1/charges'
      fullPath: '/api/v1/charges'
      preLoaderRoute: typeof ApiV1ChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/charges/$id': {
      id: '/api/v1/charges/$id'
      path: '/$id'
      fullPath: '/api/v1/charges/$id'
      preLoaderRoute: typeof ApiV1ChargesIdRouteImport
      parentRoute: typeof ApiV1ChargesRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCobrancasIdRoute: typeof AuthenticatedCobrancasIdRoute
  AuthenticatedContasIdRoute: typeof AuthenticatedContasIdRoute
  AuthenticatedContasIndexRoute: typeof AuthenticatedContasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCobrancasIdRoute: AuthenticatedCobrancasIdRoute,
  AuthenticatedContasIdRoute: AuthenticatedContasIdRoute,
  AuthenticatedContasIndexRoute: AuthenticatedContasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiV1ChargesRouteChildren {
  ApiV1ChargesIdRoute: typeof ApiV1ChargesIdRoute
}

const ApiV1ChargesRouteChildren: ApiV1ChargesRouteChildren = {
  ApiV1ChargesIdRoute: ApiV1ChargesIdRoute,
}

const ApiV1ChargesRouteWithChildren = ApiV1ChargesRoute._addFileChildren(
  ApiV1ChargesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicPicpayWebhookRoute: ApiPublicPicpayWebhookRoute,
  ApiPublicReconcileChargesRoute: ApiPublicReconcileChargesRoute,
  ApiV1ChargesRoute: ApiV1ChargesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
