/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiPublicPicpayWebhookRouteImport } from './routes/api/public/picpay-webhook'
import { Route as ApiPublicReconcileChargesRouteImport } from './routes/api/public/reconcile-charges'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPicpayWebhookRoute = ApiPublicPicpayWebhookRouteImport.update({
  id: '/api/public/picpay-webhook',
  path: '/api/public/picpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReconcileChargesRoute =
  ApiPublicReconcileChargesRouteImport.update({
    id: '/api/public/reconcile-charges',
    path: '/api/public/reconcile-charges',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/api/public/picpay-webhook': typeof ApiPublicPicpayWebhookRoute
  '/api/public/reconcile-charges': typeof ApiPublicReconcileChargesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/picpay-webhook': typeof ApiPublicPicpayWebhookRoute
  '/api/public/reconcile-charges': typeof ApiPublicReconcileChargesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/picpay-webhook': typeof ApiPublicPicpayWebhookRoute
  '/api/public/reconcile-charges': typeof ApiPublicReconcileChargesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/public/picpay-webhook'
    | '/api/public/reconcile-charges'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/api/public/picpay-webhook'
    | '/api/public/reconcile-charges'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/api/public/picpay-webhook'
    | '/api/public/reconcile-charges'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicPicpayWebhookRoute: typeof ApiPublicPicpayWebhookRoute
  ApiPublicReconcileChargesRoute: typeof ApiPublicReconcileChargesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/picpay-webhook': {
      id: '/api/public/picpay-webhook'
      path: '/api/public/picpay-webhook'
      fullPath: '/api/public/picpay-webhook'
      preLoaderRoute: typeof ApiPublicPicpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reconcile-charges': {
      id: '/api/public/reconcile-charges'
      path: '/api/public/reconcile-charges'
      fullPath: '/api/public/reconcile-charges'
      preLoaderRoute: typeof ApiPublicReconcileChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicPicpayWebhookRoute: ApiPublicPicpayWebhookRoute,
  ApiPublicReconcileChargesRoute: ApiPublicReconcileChargesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
